### ISSUE TITLE
Don't look at this if you dont want to get emotional damage

### ISSUE THREAD

**Issue by GalaxianMonster** [bichanna/Somelang#1]
You chose to view this.

I think you may make some adjustments since
it kinda looks like code from craftinginterpreters
Idea of vm kinda cool.

If you dont, its basically ok lol. (but for me it basically looks like clox idk)

**Comment by GalaxianMonster** [comment]
And also, its not ugly at all.

**Comment by bichanna** [comment]
Oh yes. I'm learning from the resource you gave me. Sorry, I forgot to say that this is just for learning purposes as you may guess from the name (somelang).

**Comment by GalaxianMonster** [comment]
Oh ok lol. Just keep reading the resource. I was also a c code copier when I knew nothing.

**Comment by GalaxianMonster** [comment]
assuming Im a beginner that time

**Comment by bichanna** [comment]
And you don't have to worry that I get emotional damage. It's fine. I'm still a young guy who's got a lot of things to learn :D

**Comment by GalaxianMonster** [comment]
Also remember the thing called

**Comment by GalaxianMonster** [comment]
ruslanspivak
Yes its basically where I learned about how to create simple interpreter

**Comment by GalaxianMonster** [comment]
Be careful with C++ though, it is where you get nightmares.

**Comment by bichanna** [comment]
Why? I haven't learned any C++.

**Comment by GalaxianMonster** [comment]
Just a reminder when you learn C++ soon.

**Comment by bichanna** [comment]
Isn't C++ an object-oriented version of C?

**Comment by GalaxianMonster** [comment]
Yes. but with many more.

**Comment by GalaxianMonster** [comment]
not just object-oriented things.

**Comment by bichanna** [comment]
Okay, I will be careful :)

**Comment by GalaxianMonster** [comment]
Sorry I wasted your time for this trashy "issue". Thanks for speaking tho.

**Comment by bichanna** [comment]
Thanks! I enjoyed the conversation.

**Comment by bichanna** [comment]
BTW, I enabled the in keyword for for loops.

**Comment by GalaxianMonster** [comment]
YES FINALLY

**Comment by GalaxianMonster** [comment]
it is basically a full language now

**Comment by GalaxianMonster** [comment]
also could you make a lexer and some parser for CGen, im lazy. sorry for adding some work :).

**Comment by GalaxianMonster** [comment]
Btw, its yours now not mine. im just contributor

**Comment by bichanna** [comment]
Okay!

**Comment by GalaxianMonster** [comment]
THANK YOU
Now i can relax

**Comment by GalaxianMonster** [comment]
Don't worry about the bytecode generation thing lol.
